#!/bin/sh
[ -f "./configure" ] && . "./configure"
[ -f "../configure" ] && . "../configure"
#$1 = model file for NCNN

# variables for total
total_layers=0
total_weights=0
total_layers=0

# per layer variables
layer_name=""
layer_num=0
layer_weights=0

NCNN_MODEL_FILE="${1}"
echo "Model complexity:"  >> ${RESULTDIR}/side_band_info.txt
echo "Model file name: ${NCNN_MODEL_FILE}"  >> ${RESULTDIR}/side_band_info.txt
printf "%-20s  %-8s %-14s\n" "layer_name" "layer_num" "weights/layer" >> ${RESULTDIR}/side_band_info.txt
printf "%-20s  %-8s  %-14s\n" "====================" "========" "=============="  >> ${RESULTDIR}/side_band_info.txt
cat "${NCNN_MODEL_FILE}" | (while read LINE; do
    set -- ${LINE}
    if [ "${1}" = "Convolution" ]; then
        layer_name="${1}"
        layer_weights=$(echo "${13}"| cut -d= -f2)
        bias=$(echo "${7}" | cut -d= -f2)
        total_weights=$((total_weights+layer_weights+bias))
        layer_num=$((layer_num+1))
        printf "%-20s  %-8s  %-14s\n" "${layer_name}" "${layer_num}" "${layer_weights}"  >> ${RESULTDIR}/side_band_info.txt
    elif [ "${1}" = "ConvolutionDepthWise" ]; then
        layer_name="${1}"
        layer_weights=$(echo "${13}"| cut -d= -f2)
        bias=$(echo "${7}" | cut -d= -f2)
        total_weights=$((total_weights+layer_weights+bias))
        layer_num=$((layer_num+1))
        printf "%-20s  %-8s  %-14s\n" "${layer_name}" "${layer_num}" "${layer_weights}" >> ${RESULTDIR}/side_band_info.txt
    elif [ "${1}" = "InnerProduct" ]; then
        layer_name="${1}"
        layer_weights=$(echo "${9}"| cut -d= -f2)
        bias=$(echo "${7}" | cut -d= -f2)
        total_weights=$((total_weights+layer_weights+bias))
        layer_num=$((layer_num+1))
        printf "%-20s  %-8s  %-14s\n" "${layer_name}" "${layer_num}" "${layer_weights}"  >> ${RESULTDIR}/side_band_info.txt
    fi
done && echo "total weights = ${total_weights}")  >> ${RESULTDIR}/side_band_info.txt
# with pipe there is subshell
# so the var inside the subshell is not recognized here
# therefore 0; fix it


